"""
Statistical analysis tools — detect data fabrication through forensic statistics.

Three core tests:
1. Benford's Law: checks if leading digits follow expected distribution.
   Fabricated numbers often deviate because humans are bad at generating random digits.
2. P-value Distribution (Caliper Test): checks for anomalous clustering of p-values
   just below 0.05 — the classic "p-hacking" signature.
3. GRIM Test: checks whether reported means are mathematically consistent with
   reported sample sizes for integer-scale data.

These are the most technically rigorous tools in the system — the mathematical
foundations are well-established in forensic statistics literature.
"""

import json
import logging
from typing import List, Optional, Any

import numpy as np
from crewai.tools import BaseTool
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


def _to_python(val: Any) -> Any:
    """Convert numpy scalar to Python native type for JSON serialization."""
    if isinstance(val, (np.integer,)):
        return int(val)
    if isinstance(val, (np.floating,)):
        return float(val)
    if isinstance(val, (np.bool_,)):
        return bool(val)
    if isinstance(val, np.ndarray):
        return val.tolist()
    return val


# ═══════════════════════════════════════════════════════════════════════
# Common Input Schema
# ═══════════════════════════════════════════════════════════════════════

class NumericDataInput(BaseModel):
    """Generic input for numeric data analysis."""

    data_values: List[float] = Field(
        ...,
        description="List of numeric values extracted from the paper (means, SDs, p-values, etc.).",
    )
    data_description: str = Field(
        default="",
        description="What these numbers represent, e.g. 'reported p-values from Table 2'.",
    )


class MeanSamplePairsInput(BaseModel):
    """Input for GRIM test: pairs of (mean, sample_size)."""

    pairs: List[dict] = Field(
        ...,
        description=(
            "List of objects, each with 'mean' (float) and 'n' (int) keys. "
            "Example: [{'mean': 3.45, 'n': 20}, {'mean': 2.78, 'n': 15}]"
        ),
    )
    data_description: str = Field(default="", description="Description of the data source.")


# ═══════════════════════════════════════════════════════════════════════
# 1. Benford's Law Test
# ═══════════════════════════════════════════════════════════════════════

class BenfordLawTool(BaseTool):
    """
    Test whether numeric data conforms to Benford's Law (First-Digit Law).

    Benford's Law states that in naturally-occurring numeric data, the leading digit
    'd' appears with probability log10(1 + 1/d). This property holds for data that
    spans multiple orders of magnitude — regression coefficients, financial data,
    population counts, physical constants, etc.

    Fabricated data often deviates significantly because humans:
    - Have digit preferences (e.g., favor 3 and 7)
    - Create numbers that are too uniformly distributed
    - Under-produce leading digit 1 (should be ~30%)

    Statistical method: Pearson's chi-squared goodness-of-fit test.
    p < 0.05 suggests possible fabrication.

    IMPORTANT: Benford's Law is NOT applicable to:
    - Data with fixed bounds (e.g., percentages, grades)
    - Data generated by sequential numbering (e.g., invoice numbers)
    - Very small datasets (n < 30)
    """

    name: str = "benford_law_test"
    description: str = (
        "Test numeric data against Benford's Law (First-Digit distribution). "
        "Fabricated data often deviates from Benford's expected digit frequencies. "
        "Applies chi-squared goodness-of-fit test. p < 0.05 flags possible fabrication. "
        "Use on: regression coefficients, means, SDs, F-statistics, total scores, "
        "count data spanning multiple orders of magnitude. "
        "DO NOT use on: bounded data (percentages, Likert scales), sequential IDs, "
        "or datasets with fewer than 30 values."
    )
    args_schema: type[BaseModel] = NumericDataInput

    def _run(self, data_values: List[float], data_description: str = "") -> str:
        """Execute Benford's Law test."""
        import numpy as np
        from scipy import stats

        # Extract first non-zero digits
        first_digits = []
        for x in data_values:
            if x == 0 or np.isnan(x) or np.isinf(x):
                continue
            x_abs = abs(x)
            # Handle scientific notation / very small numbers
            if x_abs < 1.0 and x_abs > 0:
                # Get first significant digit
                digit_str = f"{x_abs:.10f}".lstrip("0.")
                first_nonzero = next((c for c in digit_str if c != "0"), None)
                if first_nonzero:
                    first_digits.append(int(first_nonzero))
            else:
                digit_str = str(int(x_abs))
                if digit_str:
                    first_digits.append(int(digit_str[0]))

        if len(first_digits) < 30:
            return json.dumps({
                "test": "Benford's Law",
                "error": f"Insufficient data (n={len(first_digits)}, need ≥ 30).",
                "flagged": False,
                "sample_size": len(first_digits),
            })

        # Benford expected probabilities
        benford_probs = np.array([np.log10(1 + 1 / d) for d in range(1, 10)])
        observed_counts = np.array([first_digits.count(d) for d in range(1, 10)])

        # Chi-squared test
        chi2, p_value = stats.chisquare(f_obs=observed_counts, f_exp=benford_probs * len(first_digits))

        # Mean Absolute Deviation (MAD) — alternative metric
        observed_props = observed_counts / observed_counts.sum()
        mad = np.mean(np.abs(observed_props - benford_probs))

        # Conformity thresholds (Nigrini, 2012):
        # MAD < 0.006: close conformity
        # MAD 0.006-0.012: acceptable conformity
        # MAD 0.012-0.015: marginally acceptable
        # MAD > 0.015: non-conformity
        mad_assessment = (
            "close conformity" if mad < 0.006 else
            "acceptable conformity" if mad < 0.012 else
            "marginally acceptable conformity" if mad < 0.015 else
            "non-conformity — suspicious"
        )

        flagged = bool(p_value < 0.05 or mad > 0.015)

        return json.dumps({
            "test": "Benford's Law — Chi-Squared Goodness-of-Fit",
            "sample_size": int(len(first_digits)),
            "chi_squared": round(_to_python(chi2), 4),
            "degrees_of_freedom": 8,
            "p_value": round(_to_python(p_value), 6),
            "mean_absolute_deviation": round(_to_python(mad), 6),
            "mad_assessment": mad_assessment,
            "observed_distribution": {
                str(d): int(c) for d, c in zip(range(1, 10), observed_counts)
            },
            "expected_benford_distribution": {
                str(d): round(_to_python(p), 4) for d, p in zip(range(1, 10), benford_probs)
            },
            "flagged": flagged,
            "data_description": data_description,
            "interpretation": (
                f"Data significantly deviates from Benford's Law (p={_to_python(p_value):.4f}, MAD={_to_python(mad):.4f}). "
                "This is a statistical red flag for potential data fabrication."
                if flagged
                else "Data conforms to Benford's Law — no fabrication signal from digit distribution."
            ),
        }, ensure_ascii=False)


# ═══════════════════════════════════════════════════════════════════════
# 2. P-value Distribution / Caliper Test
# ═══════════════════════════════════════════════════════════════════════

class PValueDistributionTool(BaseTool):
    """
    Analyze the distribution of reported p-values for fabrication signatures.

    Under the null hypothesis, p-values should be uniformly distributed on [0, 1].
    When there are true effects, a spike near zero appears — but the rest should
    still be roughly uniform.

    Suspicious patterns:
    1. CLUSTERING JUST BELOW 0.05: The "caliper test" — if significantly more
       p-values fall in (0.045, 0.05] than in (0.05, 0.055], this suggests
       p-hacking / rounding / selective reporting.
    2. NON-UNIFORM DISTRIBUTION: Overall deviation from uniformity suggests
       the p-values were not generated by genuine statistical tests.
    3. GAPS at specific thresholds: missing values just above 0.05 or 0.01.

    Reference: Simonsohn, Nelson & Simmons (2014). "P-Curve: A Key to the File-Drawer."
    """

    name: str = "p_value_distribution_test"
    description: str = (
        "Analyze the distribution of reported p-values for anomalies. "
        "Checks for p-hacking signatures: clustering just below 0.05 (caliper test), "
        "non-uniform distribution, and gaps at significance thresholds. "
        "Use this on ALL p-values reported in the paper. "
        "Input: list of p-values extracted from the paper text and tables."
    )
    args_schema: type[BaseModel] = NumericDataInput

    def _run(self, data_values: List[float], data_description: str = "") -> str:
        """Execute p-value distribution analysis."""
        import numpy as np
        from scipy import stats

        # Clean: keep only valid p-values
        pvalues = np.array([p for p in data_values if 0 < p <= 1], dtype=np.float64)

        if len(pvalues) < 10:
            return json.dumps({
                "test": "P-value Distribution Analysis",
                "error": f"Insufficient p-values (n={len(pvalues)}, need ≥ 10).",
                "flagged": False,
                "p_value_count": len(pvalues),
            })

        findings = []

        # ── 1. Caliper Test (clustering just below 0.05) ──
        just_below_05 = int(np.sum((pvalues > 0.045) & (pvalues <= 0.05)))
        just_above_05 = int(np.sum((pvalues > 0.05) & (pvalues <= 0.055)))
        caliper_ratio = just_below_05 / max(just_above_05, 1) if just_above_05 > 0 else float('inf')

        if caliper_ratio > 2.0:
            findings.append({
                "type": "caliper_test",
                "detail": (
                    f"Discontinuity at p=0.05: {just_below_05} values in (0.045, 0.05] "
                    f"vs {just_above_05} in (0.05, 0.055]. Ratio = {caliper_ratio:.2f}."
                ),
                "suspicious": True,
            })

        # Also check 0.01 threshold
        just_below_01 = int(np.sum((pvalues > 0.009) & (pvalues <= 0.01)))
        just_above_01 = int(np.sum((pvalues > 0.01) & (pvalues <= 0.011)))
        if just_below_01 > 2 * max(just_above_01, 1):
            findings.append({
                "type": "caliper_test_001",
                "detail": (
                    f"Discontinuity at p=0.01: {just_below_01} values just below vs "
                    f"{just_above_01} just above."
                ),
                "suspicious": True,
            })

        # ── 2. Uniformity Test ──
        hist, bin_edges = np.histogram(pvalues, bins=10, range=(0, 1))
        expected_per_bin = len(pvalues) / 10
        chi2_uniform, p_uniform = stats.chisquare(
            f_obs=hist,
            f_exp=[expected_per_bin] * 10,
        )

        if p_uniform < 0.05:
            findings.append({
                "type": "uniformity_deviation",
                "detail": (
                    f"P-value distribution deviates from uniformity (χ²={chi2_uniform:.2f}, "
                    f"p={p_uniform:.4f})."
                ),
                "suspicious": True,
            })

        # ── 3. Summary Statistics ──
        median_p = float(np.median(pvalues))
        below_05_pct = float(np.mean(pvalues <= 0.05) * 100)

        # ── 4. Overall Assessment ──
        suspicious_count = len([f for f in findings if f.get("suspicious")])

        # Base suspicion on number of failed tests AND the caliper ratio
        flagged = bool(suspicious_count >= 1 or caliper_ratio > 2.0)

        # Serialize caliper_ratio: use a very large number for infinity
        caliper_ratio_serialized = (
            round(float(caliper_ratio), 4) if caliper_ratio != float('inf') else 999.0
        )

        return json.dumps({
            "test": "P-value Distribution Analysis",
            "p_value_count": int(len(pvalues)),
            "p_value_range": [round(float(pvalues.min()), 4), round(float(pvalues.max()), 4)],
            "median_p_value": round(float(median_p), 4),
            "percent_below_0.05": round(float(below_05_pct), 1),
            "caliper_test": {
                "p_values_in_0.045_to_0.05": int(just_below_05),
                "p_values_in_0.05_to_0.055": int(just_above_05),
                "caliper_ratio": caliper_ratio_serialized,
                "caliper_ratio_is_infinite": caliper_ratio == float('inf'),
                "interpretation": (
                    "Anomalous clustering just below 0.05 — potential p-hacking or selective reporting."
                    if caliper_ratio > 2.0
                    else "Normal distribution around the 0.05 threshold."
                ),
            },
            "uniformity_test": {
                "chi_squared": round(_to_python(chi2_uniform), 4),
                "p_value": round(_to_python(p_uniform), 6),
                "interpretation": (
                    "P-value distribution significantly deviates from uniformity."
                    if _to_python(p_uniform) < 0.05
                    else "P-value distribution is consistent with uniformity."
                ),
            },
            "histogram": {
                f"[{round(float(bin_edges[i]), 1)}, {round(float(bin_edges[i+1]), 1)})": int(hist[i])
                for i in range(len(hist))
            },
            "findings": findings,
            "flagged": flagged,
            "data_description": data_description,
            "interpretation": (
                f"Found {suspicious_count} suspicious pattern(s) in p-value distribution. "
                "This is a statistical red flag for p-hacking or selective reporting."
                if flagged
                else "P-value distribution appears normal — no p-hacking signal detected."
            ),
        }, ensure_ascii=False)


# ═══════════════════════════════════════════════════════════════════════
# 3. GRIM Test
# ═══════════════════════════════════════════════════════════════════════

class GRIMTestTool(BaseTool):
    """
    GRIM (Granularity-Related Inconsistency of Means) Test.

    For integer-scale data with small sample sizes, reported means are
    mathematically constrained: given N integer observations, the mean
    can only take certain fractional values.

    Specifically: mean × N must be an integer (or very close to one).
    If mean × N is not an integer, the reported mean is MATHEMATICALLY IMPOSSIBLE
    given the sample size — definitive evidence of error or fabrication.

    Example:
    - N=20, reported mean=3.45 → 3.45 × 20 = 69.0 → CONSISTENT ✓
    - N=20, reported mean=3.47 → 3.47 × 20 = 69.4 → INCONSISTENT ✗

    Reference: Brown & Heathers (2017). "The GRIM Test."
    """

    name: str = "grim_test"
    description: str = (
        "Apply the GRIM (Granularity-Related Inconsistency of Means) test. "
        "For integer-scale data with known sample sizes, checks whether reported "
        "means are mathematically possible. An inconsistent mean is DEFINITIVE proof "
        "of error/fabrication — it's a mathematical impossibility, not a statistical "
        "likelihood. Use on: means from Likert scales, counts, test scores, or any "
        "data where individual observations must be integers. "
        "Input: list of {'mean': float, 'n': int} pairs."
    )
    args_schema: type[BaseModel] = MeanSamplePairsInput

    def _run(self, pairs: List[dict], data_description: str = "") -> str:
        """Execute GRIM test on (mean, N) pairs."""
        import numpy as np

        if not pairs:
            return json.dumps({
                "test": "GRIM Test",
                "error": "No (mean, N) pairs provided.",
                "flagged": False,
            })

        results = []
        inconsistent_count = 0

        for i, pair in enumerate(pairs):
            mean = pair.get("mean")
            n = pair.get("n")

            if mean is None or n is None:
                results.append({
                    "pair_index": i,
                    "error": "Missing 'mean' or 'n' key.",
                })
                continue

            if not isinstance(n, int) or n <= 0:
                results.append({
                    "pair_index": i,
                    "mean": mean,
                    "n": n,
                    "error": "Sample size n must be a positive integer.",
                })
                continue

            # Compute: mean × N should be integer (or very close)
            product = mean * n
            nearest_integer = round(product)
            deviation = abs(product - nearest_integer)

            # Allow tiny floating-point imprecision
            is_consistent = deviation < 0.01
            if not is_consistent:
                inconsistent_count += 1

            results.append({
                "pair_index": i,
                "mean": mean,
                "n": n,
                "product": round(product, 4),
                "nearest_integer": nearest_integer,
                "deviation": round(deviation, 6),
                "consistent": is_consistent,
                "detail": (
                    f"CONSISTENT: {mean} × {n} = {product:.4f} ≈ {nearest_integer}"
                    if is_consistent
                    else f"INCONSISTENT: {mean} × {n} = {product:.4f} ≠ any integer. "
                         f"Deviation = {deviation:.4f}. This mean is MATHEMATICALLY IMPOSSIBLE "
                         f"for N={n} integer observations."
                ),
            })

        flagged = inconsistent_count > 0

        return json.dumps({
            "test": "GRIM (Granularity-Related Inconsistency of Means)",
            "pairs_tested": len(results),
            "consistent_pairs": len(results) - inconsistent_count,
            "inconsistent_pairs": inconsistent_count,
            "flagged": flagged,
            "results": results,
            "data_description": data_description,
            "interpretation": (
                f"Found {inconsistent_count} mathematically impossible mean(s). "
                "This is DEFINITIVE evidence of data fabrication"
                if flagged
                else "All reported means are mathematically consistent."
            ),
        }, ensure_ascii=False)


# ═══════════════════════════════════════════════════════════════════════
# Anomalous Precision / "Too Perfect" Data Detection
# ═══════════════════════════════════════════════════════════════════════

class AnomalousPrecisionInput(BaseModel):
    """Input for anomalous precision detection."""

    means: List[float] = Field(
        default_factory=list,
        description="List of reported means.",
    )
    sds: List[float] = Field(
        default_factory=list,
        description="List of reported standard deviations (same order as means).",
    )
    sample_sizes: List[int] = Field(
        default_factory=list,
        description="List of sample sizes (same order as means).",
    )
    p_values: List[float] = Field(
        default_factory=list,
        description="List of reported p-values.",
    )
    raw_values: List[float] = Field(
        default_factory=list,
        description="Any raw numeric values from the paper (for last-digit analysis).",
    )
    ordered_series_json: str = Field(
        default="[]",
        description=(
            "JSON string of ordered value series extracted from figures. "
            "Each series is a list of values in their natural order "
            "(e.g., bar heights from left to right in a bar chart, "
            "or dose levels from low to high). "
            "Used for near-arithmetic progression detection. "
            'Example: \'[[1200, 800, 400], [45.2, 38.1, 31.0, 23.8]]\'. '
            "Each inner list should have ≥ 3 values ordered by the figure's x-axis."
        ),
    )
    data_description: str = Field(
        default="",
        description="Description of where this data comes from.",
    )


class AnomalousPrecisionTool(BaseTool):
    """
    Detect statistical signatures of fabricated data that is "too perfect."

    Detection dimensions:
    1. SD/mean ratio: flag CV < 1% (critical) or < 3% (warning)
    2. Last-digit bias: humans fabricating numbers favor 0 and 5
       - Separate checks for "last digit = 0", "last digit = 5", and "0+5 combined"
    3. Near-arithmetic progression: check if consecutive values in ordered series
       have suspiciously constant differences (CV of diffs < threshold)
    4. High-frequency repeated values: check if any value appears suspiciously often
       in supposedly independent measurements
    5. Excessive significance rate: >80% p-values significant
    6. P-hacking clustering: too many p-values in [0.01, 0.05)
    """

    name: str = "anomalous_precision_check"
    description: str = (
        "Detect data that is 'too perfect to be true' — implausibly small standard "
        "deviations, biased last-digit distributions (separate 0 and 5 checks), "
        "near-arithmetic progressions (编造数据常呈现近似等差), "
        "high-frequency repeated values (独立实验中同一数值多次出现), "
        "excessive concentration of significant p-values. "
        "Well-established signatures of fabricated data. "
        "Provide means, SDs, sample sizes, p-values, raw values, "
        "and ordered_series_json for arithmetic progression detection."
    )
    args_schema: type[BaseModel] = AnomalousPrecisionInput

    def _run(
        self,
        means: Optional[List[float]] = None,
        sds: Optional[List[float]] = None,
        sample_sizes: Optional[List[int]] = None,
        p_values: Optional[List[float]] = None,
        raw_values: Optional[List[float]] = None,
        ordered_series_json: str = "[]",
        data_description: str = "",
    ) -> str:
        """Execute anomalous precision checks."""
        import json as _json

        means = means or []
        sds = sds or []
        p_values = p_values or []
        raw_values = raw_values or []

        # Parse ordered series
        ordered_series = []
        try:
            parsed = _json.loads(ordered_series_json)
            if isinstance(parsed, list):
                ordered_series = [
                    s for s in parsed
                    if isinstance(s, list) and len(s) >= 3
                ]
        except (_json.JSONDecodeError, TypeError):
            ordered_series = []

        findings = []
        checks_run = []
        total_checks = 0
        flagged_checks = 0

        # ── 1. SD/Mean ratio check ──
        if len(means) > 0 and len(sds) > 0 and len(means) == len(sds):
            checks_run.append("sd_mean_ratio")
            suspicious_sds = []
            for i, (m, sd) in enumerate(zip(means, sds)):
                if m != 0 and sd >= 0:
                    cv = abs(sd / m)
                    if cv < 0.01:
                        suspicious_sds.append({
                            "index": i, "mean": m, "sd": sd,
                            "cv": round(cv, 4), "severity": "critical",
                            "detail": f"CV={cv*100:.2f}% — implausibly precise.",
                        })
                        flagged_checks += 1
                    elif cv < 0.03:
                        suspicious_sds.append({
                            "index": i, "mean": m, "sd": sd,
                            "cv": round(cv, 4), "severity": "warning",
                            "detail": f"CV={cv*100:.2f}% — unusually low.",
                        })
                        flagged_checks += 1
            total_checks += len(means)
            if suspicious_sds:
                findings.append({
                    "check": "sd_mean_ratio",
                    "finding": f"{len(suspicious_sds)}/{len(means)} mean-SD pairs "
                               f"have suspiciously low CV.",
                    "details": suspicious_sds,
                })

        # ── 2. Last-digit preference analysis (强化版：独立检测末位0和末位5) ──
        if len(raw_values) >= 10:
            checks_run.append("last_digit_analysis")
            last_digits = []
            for v in raw_values:
                v_str = f"{abs(v):.10g}"
                if "." in v_str:
                    frac = v_str.split(".")[1]
                    if frac:
                        last_digits.append(int(frac[-1]))
                elif v_str[-1].isdigit():
                    last_digits.append(int(v_str[-1]))

            if len(last_digits) >= 10:
                from collections import Counter
                digit_counts = Counter(last_digits)
                total = len(last_digits)
                digit_freqs = {
                    str(d): round(digit_counts.get(d, 0) / total, 3)
                    for d in range(10)
                }
                biased = {d: round(f, 3) for d, f in digit_freqs.items()
                          if float(f) > 0.20}

                # 独立检测末位=0和末位=5
                freq_0 = digit_freqs.get("0", 0)
                freq_5 = digit_freqs.get("5", 0)
                zero_five = freq_0 + freq_5
                expected_per_digit = 0.10  # uniform expectation

                digit_flags = []
                # 末位=5 独立检测（编造数据中5是最高频的偏好数字之一）
                if freq_5 > 0.20:
                    digit_flags.append(
                        f"末位=5 占比 {freq_5:.1%}（期望 10%），"
                        f"是期望值的 {freq_5/0.10:.1f} 倍"
                    )
                    flagged_checks += 1
                elif freq_5 > 0.15:
                    digit_flags.append(
                        f"末位=5 占比 {freq_5:.1%}（期望 10%），轻度偏高"
                    )
                    flagged_checks += 1

                # 末位=0 独立检测
                if freq_0 > 0.20:
                    digit_flags.append(
                        f"末位=0 占比 {freq_0:.1%}（期望 10%），"
                        f"是期望值的 {freq_0/0.10:.1f} 倍"
                    )
                    flagged_checks += 1

                # 组合检测
                if zero_five > 0.35:
                    digit_flags.append(
                        f"末位0+5合计占比 {zero_five:.1%}（期望 20%）"
                    )
                    if not digit_flags:
                        flagged_checks += 1

                # 其他偏好的数字
                if biased:
                    if not digit_flags:
                        flagged_checks += 1

                total_checks += 1
                if digit_flags or biased:
                    findings.append({
                        "check": "last_digit_analysis",
                        "finding": "末位数字分布异常。 " + "；".join(digit_flags) if digit_flags else (
                            f"Over-represented digits: {biased}."
                        ),
                        "digit_frequencies": digit_freqs,
                        "last_digit_5_frequency": freq_5,
                        "last_digit_0_frequency": freq_0,
                        "zero_five_combined": round(zero_five, 3),
                        "overrepresented_digits": biased,
                        "n_analyzed": total,
                        "interpretation": (
                            "人为编造的数据通常呈现末位数字偏好，"
                            "尤其是末位=5（如 1.5, 2.5, 3.5...）和末位=0，"
                            "因为人类倾向于选择'整齐'或'中间'的数字。"
                        ),
                    })

        # ── 2.5. 近等差数列检测 (Near-Arithmetic Progression Detection) ──
        # 编造数据最常见的模式：逐组递减/递增固定量
        # 真实数据相邻差值波动大，编造数据差值高度一致
        if ordered_series:
            checks_run.append("near_arithmetic_progression")
            progression_flags = []
            for si, series in enumerate(ordered_series):
                if len(series) < 3:
                    continue
                vals = np.array(series, dtype=np.float64)
                # 计算相邻差值
                diffs = np.diff(vals)
                diff_mean = float(np.mean(np.abs(diffs)))
                diff_std = float(np.std(diffs))

                if diff_mean < 1e-10:
                    # 所有值完全相同 → 由 cross_figure_data_compare 处理
                    continue

                # 核心指标：差值的变异系数 CV_diff = std(diffs) / |mean(diffs)|
                # CV_diff 越小 → 差值越一致 → 越像等差数列
                cv_diff = float(diff_std / diff_mean) if diff_mean > 1e-10 else 0.0

                # 完美等差数列：CV_diff = 0
                # 近似等差数列：CV_diff < 0.10（差值波动不到均值的10%）
                # 可疑：CV_diff < 0.20

                severity = None
                if cv_diff < 0.05:
                    severity = "critical"
                elif cv_diff < 0.10:
                    severity = "high"
                elif cv_diff < 0.20:
                    severity = "medium"

                if severity:
                    # 计算如果差值是完美等差数列的拟合优度
                    n = len(vals)
                    # 完美等差: y = a + b*x where b = (last-first)/(n-1)
                    perfect_step = (vals[-1] - vals[0]) / (n - 1)
                    perfect_vals = np.array([
                        vals[0] + perfect_step * k for k in range(n)
                    ])
                    residuals = np.abs(vals - perfect_vals)
                    max_residual = float(np.max(residuals))
                    # R² of fit to perfect arithmetic progression
                    ss_res = float(np.sum((vals - perfect_vals) ** 2))
                    ss_tot = float(np.sum((vals - np.mean(vals)) ** 2))
                    r_squared = float(1 - ss_res / ss_tot) if ss_tot > 1e-10 else 1.0

                    progression_flags.append({
                        "series_index": si,
                        "values": [round(float(v), 4) for v in vals],
                        "n_values": n,
                        "diffs": [round(float(d), 4) for d in diffs],
                        "diff_mean": round(diff_mean, 4),
                        "diff_std": round(diff_std, 4),
                        "cv_of_diffs": round(cv_diff, 6),
                        "perfect_step": round(float(perfect_step), 4),
                        "max_residual_from_perfect": round(max_residual, 6),
                        "r_squared_to_perfect_ap": round(r_squared, 6),
                        "severity": severity,
                        "interpretation": (
                            f"该序列的相邻差值变异系数 CV={cv_diff:.4f}，"
                            f"R² 对完美等差数列 = {r_squared:.6f}。"
                            f"差值: {[round(float(d), 2) for d in diffs]}。"
                            + (
                                f"差值近乎恒定（CV={cv_diff:.4f}），"
                                f"呈现典型的近似等差数列特征 — "
                                f"这是人为编造数据的最强信号之一。"
                                f"真实生物实验数据几乎不可能出现差值如此一致的序列。"
                                if cv_diff < 0.10
                                else f"差值较为一致（CV={cv_diff:.4f}），"
                                f"存在人为编造数据的可能性。"
                            )
                        ),
                    })

            total_checks += len(ordered_series)
            if progression_flags:
                # Count as flagged per series with flags
                flagged_checks += len(progression_flags)
                findings.append({
                    "check": "near_arithmetic_progression",
                    "finding": (
                        f"{len(progression_flags)}/{len(ordered_series)} 个有序序列"
                        f"呈现近等差数列特征。"
                    ),
                    "progression_details": progression_flags,
                    "interpretation": (
                        "近等差数列（相邻差值高度一致）是人为编造数据的经典指纹。"
                        "真实实验数据由于生物变异和测量误差，"
                        "相邻数据点的差值几乎不可能高度一致。"
                        "差值变异系数 CV_diff < 0.10 时高度可疑，"
                        "< 0.05 时几乎可以确定是编造的。"
                    ),
                })

        # ── 2.6. 高频重复值检测 (High-Frequency Repeated Values) ──
        if len(raw_values) >= 6:
            checks_run.append("high_frequency_repeats")
            from collections import Counter as _Counter
            val_counter = _Counter(raw_values)
            n_unique = len(val_counter)
            n_total = len(raw_values)

            # 如果一个值在数据集中出现 ≥3 次且占比 > 20%，高度可疑
            # 多个"独立"实验不应该产生完全相同的测量值
            repeat_flags = []
            for val, count in val_counter.most_common():
                freq = count / n_total
                if count >= 3 and freq > 0.15:
                    repeat_flags.append({
                        "value": val,
                        "count": count,
                        "frequency": round(freq, 4),
                        "severity": "critical" if count >= 4 and freq > 0.25 else "high",
                        "interpretation": (
                            f"数值 {val} 在数据集中出现 {count} 次 "
                            f"（占比 {freq:.1%}）。"
                            + (
                                f"这在声称的独立实验中极不合理 "
                                f"— 真实独立测量产生完全相同数值的概率极低。"
                                if count >= 4
                                else "可能不是独立实验产生。"
                            )
                        ),
                    })

            total_checks += 1
            if repeat_flags:
                flagged_checks += 1
                findings.append({
                    "check": "high_frequency_repeats",
                    "finding": (
                        f"发现 {len(repeat_flags)} 个数值在数据集中高频重复出现，"
                        f"与独立实验的预期不符。"
                    ),
                    "repeat_details": repeat_flags,
                    "dataset_summary": {
                        "total_values": n_total,
                        "unique_values": n_unique,
                        "uniqueness_ratio": round(n_unique / n_total, 4),
                    },
                    "interpretation": (
                        "真实独立实验由于生物变异、测量误差和随机因素，"
                        "几乎不可能产生完全相同的测量值。"
                        "同一数值多次出现（≥3次且占比>15%）说明数据可能被复制粘贴。"
                    ),
                })

        # ── 3. P-value significance concentration ──
        if len(p_values) >= 5:
            checks_run.append("significance_concentration")
            sig_count = sum(1 for p in p_values if p < 0.05)
            just_sig = sum(1 for p in p_values if 0.01 <= p < 0.05)
            total_p = len(p_values)
            sig_rate = sig_count / total_p if total_p > 0 else 0

            total_checks += 1
            if sig_rate > 0.80:
                flagged_checks += 1
                findings.append({
                    "check": "significance_concentration",
                    "finding": f"{sig_count}/{total_p} ({sig_rate:.1%}) p-values "
                               f"significant — unusually high rate.",
                    "significant_rate": round(sig_rate, 3),
                })

            if just_sig >= 3 and just_sig / max(total_p, 1) > 0.4:
                flagged_checks += 1
                findings.append({
                    "check": "p_hacking_clustering",
                    "finding": f"{just_sig}/{total_p} p-values cluster in [0.01, 0.05) — "
                               f"classic p-hacking signature.",
                })

        return json.dumps({
            "test": "Anomalous Precision & Fabrication Indicators",
            "data_description": data_description,
            "checks_run": checks_run,
            "total_checks": total_checks,
            "flagged_checks": flagged_checks,
            "flagged": flagged_checks > 0,
            "findings": findings,
            "interpretation": (
                f"{flagged_checks}/{total_checks} checks flagged. "
                + ("Suspicious patterns detected." if flagged_checks > 0
                   else "No anomalous precision indicators detected.")
            ),
        }, ensure_ascii=False)


# ═══════════════════════════════════════════════════════════════════════
# Statistical Consistency Verification
# ═══════════════════════════════════════════════════════════════════════

class StatisticalConsistencyInput(BaseModel):
    """Input for statistical consistency verification."""

    test_statistics: str = Field(
        default="[]",
        description=(
            "JSON list of test statistic objects. Each object: "
            '"test_type" ("t","F","chi2","r"), '
            '"value" (test statistic), "df" or "df1"/"df2", '
            '"reported_p" (optional), "reported_n" (optional). '
            'Example: [{"test_type":"t","value":2.45,"df":28,"reported_p":0.021}]'
        ),
    )
    data_description: str = Field(default="", description="Data source description.")


class StatisticalConsistencyTool(BaseTool):
    """
    Verify internal consistency of reported statistical results.

    1. t/F/chi2 consistency: given stat and df, verify reported p-value
    2. df vs N consistency: df should match N-1 (one-sample) or N-2 (two-sample)
    3. Impossible values: negative F/chi2, |r| > 1
    """

    name: str = "statistical_consistency_check"
    description: str = (
        "Verify reported statistical results are internally consistent. "
        "Checks if t/F/chi2 value with reported df gives the reported p-value, "
        "if df matches sample size, and if any values are mathematically impossible. "
        "Fabricators often invent inconsistent (stat, df, p) triplets."
    )
    args_schema: type[BaseModel] = StatisticalConsistencyInput

    def _run(
        self,
        test_statistics: str = "[]",
        data_description: str = "",
    ) -> str:
        """Execute statistical consistency checks."""
        try:
            stats_list = json.loads(test_statistics)
            if not isinstance(stats_list, list):
                return json.dumps({
                    "error": "test_statistics must be a JSON list.", "flagged": False,
                })
        except json.JSONDecodeError:
            return json.dumps({
                "error": "test_statistics must be valid JSON.", "flagged": False,
            })

        if not stats_list:
            return json.dumps({
                "test": "Statistical Consistency Verification",
                "data_description": data_description,
                "statistics_checked": 0,
                "flagged": False,
                "findings": [],
                "interpretation": "No test statistics provided.",
            })

        from scipy import stats as scipy_stats

        findings = []
        flagged_count = 0
        results = []

        for i, s in enumerate(stats_list):
            test_type = s.get("test_type", "").lower()
            value = s.get("value")
            df = s.get("df")
            df1 = s.get("df1")
            df2 = s.get("df2")
            reported_p = s.get("reported_p")
            reported_n = s.get("reported_n")

            result = {"index": i, "test_type": test_type, "value": value, "issues": []}

            # Basic validity
            if value is not None:
                if test_type == "F" and value < 0:
                    result["issues"].append("F-statistic cannot be negative.")
                if test_type == "chi2" and value < 0:
                    result["issues"].append("Chi-squared cannot be negative.")
                if test_type == "r" and abs(value) > 1:
                    result["issues"].append("|r| > 1 is impossible.")

            # P-value consistency
            if value is not None and reported_p is not None:
                try:
                    computed_p = None
                    if test_type == "t" and df is not None:
                        computed_p = float(2 * scipy_stats.t.sf(abs(value), df))
                    elif test_type == "F" and df1 is not None and df2 is not None:
                        computed_p = float(scipy_stats.f.sf(value, df1, df2))
                    elif test_type == "chi2" and df is not None:
                        computed_p = float(scipy_stats.chi2.sf(value, df))

                    if computed_p is not None:
                        result["computed_p"] = round(computed_p, 6)
                        result["reported_p"] = reported_p
                        ratio = (
                            max(computed_p, reported_p) / min(computed_p, reported_p)
                            if min(computed_p, reported_p) > 1e-300 else float("inf")
                        )
                        if ratio > 10:
                            result["issues"].append(
                                f"p mismatch: reported={reported_p}, "
                                f"computed={computed_p:.6f} (ratio={ratio:.1f}x)"
                            )
                            flagged_count += 1
                except Exception:
                    pass

            # df vs N
            if df is not None and reported_n is not None and test_type == "t":
                exp1 = reported_n - 1
                exp2 = reported_n - 2 if reported_n >= 2 else None
                if df != exp1 and (exp2 is None or df != exp2):
                    result["issues"].append(
                        f"df={df} vs N={reported_n}: expected df≈{exp1} "
                        f"(one-sample) or df≈{exp2} (two-sample)"
                    )

            if result["issues"]:
                flagged_count += 1
                findings.append(result)
            results.append(result)

        return json.dumps({
            "test": "Statistical Consistency Verification",
            "data_description": data_description,
            "statistics_checked": len(stats_list),
            "flagged": flagged_count > 0,
            "inconsistent_count": flagged_count,
            "findings": findings,
            "all_results": results,
            "interpretation": (
                f"{flagged_count}/{len(stats_list)} test statistic(s) internally "
                "inconsistent — strong evidence of fabrication."
                if flagged_count > 0
                else "All checked test statistics are internally consistent."
            ),
        }, ensure_ascii=False)


# ═══════════════════════════════════════════════════════════════════════════
# Cross-Figure Data Comparison
# ═══════════════════════════════════════════════════════════════════════════

class CrossFigureDataInput(BaseModel):
    """Input for cross-figure data comparison."""

    datasets_json: str = Field(
        ...,
        description=(
            "JSON string representing a list of datasets to compare. Each dataset "
            "should have 'label' (figure name/ID), 'group_labels' (list of group names "
            "like ['Control','Treatment1','Treatment2']), and 'values' (list of numeric "
            "values corresponding to each group). "
            'Example: \'[{"label":"Fig1E","group_labels":["Control","COH","COH+RTA"],'
            '"values":[1200,800,400]},{"label":"Fig4B","group_labels":["Control","COH",'
            '"COH+RTA"],"values":[1200,800,400]}]\''
        ),
    )
    tolerance: float = Field(
        default=0.001,
        ge=0.0,
        le=1.0,
        description="Relative tolerance for 'near match' detection. 0 = exact match only.",
    )


class CrossFigureDataComparisonTool(BaseTool):
    """
    Detect data duplication across different figures by comparing numeric values.

    THIS IS THE MOST POWERFUL TOOL for catching the #1 data fabrication pattern:
    the same dataset presented as different experiments in different figures.

    Example (real case, RTA408 paper, retracted by PLOS ONE):
    - Figure 1E: Control=1200, COH=800, COH+RTA408=400
    - Figure 4B: Control=1200, COH=800, COH+RTA408=400
    → EXACT MATCH across figures claiming to be independent experiments.
    → Mathematically impossible without fabrication.

    How it works:
    1. For each pair of datasets, compute similarity metrics.
    2. Check for: exact match, near match (within tolerance), subset match,
       ratio match (one dataset = constant × another).
    3. Report any statistically impossible matches.

    Use this on ALL extracted numeric data from ALL figures.
    """

    name: str = "cross_figure_data_compare"
    description: str = (
        "Compare numeric data across different figures to detect duplication. "
        "This catches the classic fraud pattern where the same experimental data "
        "is presented as multiple independent experiments. Feed it datasets from "
        "different figures (extracted via chart_ocr or table_extraction) and it "
        "will flag ANY exact or near-exact matches between supposedly independent "
        "experiments — which is mathematically impossible in real biological data. "
        "Input: JSON list of datasets with labels, group_labels, and values. "
        "CRITICAL: Run this on ALL extracted numeric data from ALL figures."
    )
    args_schema: type[BaseModel] = CrossFigureDataInput

    def _run(self, datasets_json: str, tolerance: float = 0.001) -> str:
        """Execute cross-figure data comparison."""
        import numpy as np

        try:
            datasets = json.loads(datasets_json)
            if not isinstance(datasets, list) or len(datasets) < 2:
                return json.dumps({
                    "error": "Need at least 2 datasets as a JSON list.",
                    "flagged": False,
                })
        except json.JSONDecodeError as e:
            return json.dumps({"error": f"Invalid JSON: {e}", "flagged": False})

        # Validate datasets
        for d in datasets:
            if "values" not in d:
                return json.dumps({
                    "error": "Each dataset must have 'values' field.",
                    "flagged": False,
                })

        matches = []
        for i in range(len(datasets)):
            for j in range(i + 1, len(datasets)):
                d_a = datasets[i]
                d_b = datasets[j]
                vals_a = np.array(d_a.get("values", []), dtype=np.float64)
                vals_b = np.array(d_b.get("values", []), dtype=np.float64)

                if len(vals_a) == 0 or len(vals_b) == 0:
                    continue

                # ── Check 1: Exact match ──
                if len(vals_a) == len(vals_b):
                    if np.allclose(vals_a, vals_b, rtol=0, atol=0):
                        matches.append({
                            "type": "exact_match",
                            "dataset_a": d_a.get("label", f"dataset_{i}"),
                            "dataset_b": d_b.get("label", f"dataset_{j}"),
                            "shared_values": vals_a.tolist(),
                            "group_labels_a": d_a.get("group_labels", []),
                            "group_labels_b": d_b.get("group_labels", []),
                            "confidence": "critical",
                            "interpretation": (
                                f"CRITICAL: {d_a.get('label')} and {d_b.get('label')} "
                                f"have IDENTICAL values. Independent biological "
                                f"experiments CANNOT produce perfectly identical "
                                f"results. This is definitive evidence of data "
                                f"fabrication or duplication."
                            ),
                        })
                        continue

                # ── Check 2: Near match (within tolerance) ──
                if len(vals_a) == len(vals_b) and tolerance > 0:
                    rel_diff = np.abs(vals_a - vals_b) / np.maximum(
                        np.abs(vals_a), np.abs(vals_b)
                    )
                    rel_diff = np.nan_to_num(rel_diff, nan=0.0)
                    if np.all(rel_diff <= tolerance):
                        matches.append({
                            "type": "near_match",
                            "dataset_a": d_a.get("label", f"dataset_{i}"),
                            "dataset_b": d_b.get("label", f"dataset_{j}"),
                            "values_a": vals_a.tolist(),
                            "values_b": vals_b.tolist(),
                            "max_relative_difference": round(float(np.max(rel_diff)), 6),
                            "tolerance": tolerance,
                            "confidence": "high" if np.max(rel_diff) < 0.001 else "medium",
                            "interpretation": (
                                f"HIGH: {d_a.get('label')} and {d_b.get('label')} "
                                f"have nearly identical values (max diff "
                                f"{np.max(rel_diff):.4%}). Real independent "
                                f"experiments should show natural variability."
                            ),
                        })

                # ── Check 3: Subset match ──
                # Check if one dataset's values are a subset of the other
                min_len = min(len(vals_a), len(vals_b))
                if min_len >= 2:
                    # Try all possible contiguous subsets
                    longer = vals_a if len(vals_a) >= len(vals_b) else vals_b
                    shorter = vals_b if len(vals_a) >= len(vals_b) else vals_a
                    longer_label = d_a.get("label") if len(vals_a) >= len(vals_b) else d_b.get("label")
                    shorter_label = d_b.get("label") if len(vals_a) >= len(vals_b) else d_a.get("label")

                    for start in range(len(longer) - len(shorter) + 1):
                        subset = longer[start:start + len(shorter)]
                        if np.allclose(subset, shorter, rtol=tolerance, atol=0):
                            matches.append({
                                "type": "subset_match",
                                "superset": longer_label,
                                "subset": shorter_label,
                                "shared_values": shorter.tolist(),
                                "position_in_superset": start,
                                "confidence": "high",
                                "interpretation": (
                                    f"HIGH: All values from {shorter_label} appear "
                                    f"identically in {longer_label} (at position "
                                    f"{start}). Suggests data copying with "
                                    f"additional groups added."
                                ),
                            })
                            break

                # ── Check 4: Ratio/proportional match ──
                if len(vals_a) == len(vals_b) and len(vals_a) >= 2:
                    # Check if values differ by a constant ratio
                    ratios = np.where(
                        np.abs(vals_b) > 1e-10,
                        vals_a / vals_b,
                        np.nan,
                    )
                    ratios = ratios[~np.isnan(ratios)]
                    if len(ratios) >= 2:
                        ratio_mean = np.mean(ratios)
                        ratio_std = np.std(ratios)
                        if ratio_std < 0.01 * abs(ratio_mean) and abs(ratio_mean - 1.0) > 0.01:
                            matches.append({
                                "type": "ratio_match",
                                "dataset_a": d_a.get("label", f"dataset_{i}"),
                                "dataset_b": d_b.get("label", f"dataset_{j}"),
                                "ratio": round(float(ratio_mean), 4),
                                "ratio_std": round(float(ratio_std), 6),
                                "confidence": "medium",
                                "interpretation": (
                                    f"MEDIUM: Values in {d_a.get('label')} are "
                                    f"{ratio_mean:.2f}× those in {d_b.get('label')} "
                                    f"with very low variance. Could indicate "
                                    f"systematic scaling rather than genuine data."
                                ),
                            })

                # ── Check 5: Shared group names (label-only comparison) ──
                groups_a = set(d_a.get("group_labels", []))
                groups_b = set(d_b.get("group_labels", []))
                common_groups = groups_a & groups_b

                if common_groups and len(vals_a) == len(vals_b) == len(common_groups):
                    # Both have same groups, compare values for those groups
                    idx_a = [d_a["group_labels"].index(g) for g in common_groups if g in d_a["group_labels"]]
                    idx_b = [d_b["group_labels"].index(g) for g in common_groups if g in d_b["group_labels"]]
                    if len(idx_a) == len(idx_b) and len(idx_a) >= 2:
                        shared_a = np.array([vals_a[k] for k in idx_a])
                        shared_b = np.array([vals_b[k] for k in idx_b])
                        if np.allclose(shared_a, shared_b, rtol=0, atol=0):
                            matches.append({
                                "type": "shared_group_exact_match",
                                "dataset_a": d_a.get("label", f"dataset_{i}"),
                                "dataset_b": d_b.get("label", f"dataset_{j}"),
                                "common_groups": sorted(common_groups),
                                "shared_values": shared_a.tolist(),
                                "confidence": "critical",
                                "interpretation": (
                                    f"CRITICAL: Groups {sorted(common_groups)} have "
                                    f"IDENTICAL values in both {d_a.get('label')} "
                                    f"and {d_b.get('label')}. This is the exact "
                                    f"pattern found in the retracted RTA408 paper "
                                    f"(Fig 1E vs Fig 4B: Control, COH, COH+RTA408 "
                                    f"data identical). Definitive fabrication evidence."
                                ),
                            })

        # ── Build result ──
        flagged = len(matches) > 0
        critical_count = sum(1 for m in matches if m["confidence"] == "critical")
        high_count = sum(1 for m in matches if m["confidence"] == "high")

        result = {
            "analysis_type": "Cross-Figure Data Comparison",
            "datasets_compared": len(datasets),
            "dataset_labels": [d.get("label", f"dataset_{i}") for i, d in enumerate(datasets)],
            "comparisons_made": len(datasets) * (len(datasets) - 1) // 2,
            "flagged": flagged,
            "total_matches": len(matches),
            "critical_matches": critical_count,
            "high_matches": high_count,
            "tolerance_used": tolerance,
            "matches": matches,
            "interpretation": (
                f"CRITICAL FINDING: {len(matches)} instance(s) of data duplication "
                f"detected ({critical_count} critical, {high_count} high confidence). "
                "This is definitive evidence of data fabrication — the same numbers "
                "appear in supposedly independent experiments. Immediate investigation "
                "and potential retraction recommended."
                if flagged
                else "No data duplication detected across figures. All compared "
                "datasets have unique values within the specified tolerance."
            ),
        }
        return json.dumps(result, ensure_ascii=False)
